# Generated by Django 4.1.1 on 2022-10-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_packageenroled_student_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tutor_images'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.package'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.tutor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='student_images'),
        ),
    ]
