# Generated by Django 4.1.1 on 2022-10-09 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_tutor_image_alter_packageenroled_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_id',
            field=models.CharField(default=students.models.generate_student_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='students.package'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='packageenroled',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor', to='students.tutor'),
        ),
    ]
